package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"github.com/gari8/gql-with-loader/entity"
	"github.com/gari8/gql-with-loader/graph"
)

// Members is the resolver for the members field.
func (r *groupResolver) Members(ctx context.Context, obj *entity.Group, status *entity.Status) ([]*entity.Member, error) {
	return r.Loaders.LoadMembers(ctx, obj.ID, status)
}

// Groups is the resolver for the groups field.
func (r *queryResolver) Groups(ctx context.Context) ([]*entity.Group, error) {
	return r.GroupRepo.FindAll(nil)
}

// Group returns graph.GroupResolver implementation.
func (r *Resolver) Group() graph.GroupResolver { return &groupResolver{r} }

type groupResolver struct{ *Resolver }
