package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.24

import (
	"context"
	"github.com/gari8/gql-with-loader/entity"
	"github.com/gari8/gql-with-loader/graph"
)

// Group is the resolver for the group field.
func (r *memberResolver) Group(ctx context.Context, obj *entity.Member) (*entity.Group, error) {
	return r.Loaders.LoadGroup(ctx, obj.GroupID)
}

// Members is the resolver for the members field.
func (r *queryResolver) Members(ctx context.Context, status *entity.Status) ([]*entity.Member, error) {
	return r.MemberRepo.FindAll(status, nil)
}

// Member returns graph.MemberResolver implementation.
func (r *Resolver) Member() graph.MemberResolver { return &memberResolver{r} }

type memberResolver struct{ *Resolver }
